"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2

[[blocks]]
type = "rprompt"
overflow = 'hidden'

  [[blocks.segments]]
  foreground = "#00C5C7"
  style = "plain"
  template = " {{ .CurrentDate | date .Format }} "
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#ffa500'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  foreground = "#00C5C7"
  style = "plain"
  template = "{{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  foreground = "#ffa500"
  style = "plain"
  template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"
  type = "git"

  [blocks.segments.properties]
  branch_icon = ''
  commit_icon = '@'
  fetch_status = true

  [[blocks.segments]]
  style = "plain"
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}#43D426{{end}}",
  ]
  template = "❯ "
  type = "text"

[transient_prompt]
  background = "transparent"
  foreground = "#ffffff"
  template = "❯ "
